# Generated by Django 2.2 on 2019-04-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=50, verbose_name='文章标题')),
                ('atime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('auser', models.CharField(max_length=20, verbose_name='发布人')),
                ('anum', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('acontent', models.TextField(verbose_name='文章内容')),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, verbose_name='总标签')),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50, verbose_name='评论人')),
                ('pemile', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('purl', models.URLField(verbose_name='网址')),
                ('pcontent', models.TextField(verbose_name='评论内容')),
                ('ptime', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('paid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articletest.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='akind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articletest.Kind', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='article',
            name='alabel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articletest.Lable', verbose_name='标签外键'),
        ),
    ]
